apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-product-fetch
spec:
  entrypoint: argo-product-fetch
  templates:
  - name: argo-product-fetch
    steps:
    - - name: generate-artifact
        template: fetch
    - - name: consume-artifact
        template: notify
        arguments:
          artifacts:
          - name: products
            from: "{{steps.generate-artifact.outputs.artifacts.products}}"

  - name: fetch
    container:
      image: ghcr.io/dominikus1993/argo-rossmann-product-fetcher-fetch-cli:main
      command: ["dotnet"]
      args: ["ProductFetcher.FetchCli.dll"]
      env: 
        - name: WriteSink__Path
          value: /mnt/out
        - name: WriteSink__Filename
          value: products.json
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      artifacts:
      - name: products
        path: /mnt/out/products.json

  - name: notify
    inputs:
      artifacts:
      - name: products
        path: /mnt/out/products.json
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /mnt/out/products.json"]
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }